from os import path


def main():

    print("Generating PortableMC Core script... ", end='')

    this_dir = path.dirname(__file__)
    pmc_file = path.join(this_dir, "portablemc.py")
    pmc_core_file = path.join(this_dir, "portablemc_core.py")

    with open(pmc_file, "rt") as src:
        with open(pmc_core_file, "wt") as dst:
            while True:
                line = src.readline()
                if not len(line) or line.startswith("if __name__ == '__main__':"):
                    break
                dst.write(line)
                if line.startswith("# encoding: utf8"):
                    dst.write("\n"
                              "# This file is not intended to be modified manually, it was generated by 'gen_core.py'.\n"
                              "# You must develop the 'portablemc.py' script and then start 'gen_core.py' to regenerate this lib.\n")

    print("Done.")

if __name__ == '__main__':
    main()
