# This file was generated by PortableMC.
# It's only purpose is to make this directory a valid python package.
# Do not modify this file unless you know what you are doing, because this file is not intended to be shared.
