from typing import Self
from os import PathLike
from uuid import UUID
from enum import Enum, auto

from . import base, msa


class Installer(base.Installer):

    def __new__(cls, version: str | Version = Version.Release) -> Self: ...

    def __repr__(self) -> str: ...

    @base.Installer.version.getter
    def version(self) -> str | Version: ...
    @version.setter
    def version(self, version: str | Version): ...

    # TODO: fetch exclude

    @property
    def demo(self) -> bool: ...
    @demo.setter
    def demo(self, demo: bool): ...
    
    @property
    def quick_play(self) -> QuickPlay | None: ...
    @quick_play.setter
    def quick_play(self, quick_play: QuickPlay | None): ...
    
    @property
    def resolution(self) -> tuple[int, int] | None: ...
    @resolution.setter
    def resolution(self, resolution: tuple[int, int] | None): ...
    
    @property
    def disable_multiplayer(self) -> bool: ...
    @disable_multiplayer.setter
    def disable_multiplayer(self, disable_multiplayer: bool): ...

    @property
    def disable_chat(self) -> bool: ...
    @disable_chat.setter
    def disable_chat(self, disable_chat: bool): ...

    @property
    def auth_uuid(self) -> bool: ...
    @property
    def auth_username(self) -> bool: ...

    def set_auth_offline(self, uuid: UUID, username: str) -> None: ...
    def set_auth_offline_uuid(self, uuid: UUID) -> None: ...
    def set_auth_offline_username(self, username: str) -> None: ...
    def set_auth_offline_hostname(self) -> None: ...
    def set_auth_msa(self, account: msa.Account) -> None: ...

    @property
    def client_id(self) -> str: ...
    @client_id.setter
    def client_id(self, client_id: str): ...

    @property
    def fix_legacy_quick_play(self) -> bool: ...
    @fix_legacy_quick_play.setter
    def fix_legacy_quick_play(self, fix: bool): ...

    @property
    def fix_legacy_proxy(self) -> bool: ...
    @fix_legacy_proxy.setter
    def fix_legacy_proxy(self, fix: bool): ...

    @property
    def fix_legacy_merge_sort(self) -> bool: ...
    @fix_legacy_merge_sort.setter
    def fix_legacy_merge_sort(self, fix: bool): ...

    @property
    def fix_legacy_resolution(self) -> bool: ...
    @fix_legacy_resolution.setter
    def fix_legacy_resolution(self, fix: bool): ...

    @property
    def fix_broken_authlib(self) -> bool: ...
    @fix_broken_authlib.setter
    def fix_broken_authlib(self, fix: bool): ...

    @property
    def fix_lwjgl(self) -> str | None: ...
    @fix_lwjgl.setter
    def fix_lwjgl(self, lwjgl_version: str | None): ...

    def install(self) -> base.Game: ...


class Version(Enum):
    Release = auto()
    Snapshot = auto()


class QuickPlay:
    class Path(QuickPlay):
        def __new__(cls, path: str | PathLike[str]) -> Self: ...
    class Singleplayer(QuickPlay):
        def __new__(cls, name: str) -> Self: ...
    class Multiplayer(QuickPlay):
        def __new__(cls, host: str, port: int) -> Self: ...
    class Realms(QuickPlay):
        def __new__(cls, id: str) -> Self: ...
