from typing import Self, Iterator
from uuid import UUID
from os import PathLike


class Auth:

    def __new__(cls, app_id: str) -> Self: ...

    def __repr__(self) -> str: ...

    def request_device_code(self) -> DeviceCodeFlow: ...


class DeviceCodeFlow:

    def __repr__(self) -> str: ...

    @property
    def user_code(self) -> str: ...
    @property
    def verification_uri(self) -> str: ...
    @property
    def message(self) -> str: ...

    def wait(self) -> Account: ...


class Account:

    def __repr__(self) -> str: ...

    @property
    def app_id(self) -> str: ...
    @property
    def access_token(self) -> str: ...
    @property
    def uuid(self) -> UUID: ...
    @property
    def username(self) -> str: ...
    @property
    def xuid(self) -> str: ...

    def request_profile(self) -> None: ...

    def request_refresh(self) -> None: ...


class Database:

    def __new__(cls, file: str | PathLike[str]) -> Self: ...

    def __repr__(self) -> str: ...
    
    @property
    def file(self) -> str: ...

    def load_iter(self) -> Iterator[Account]: ...

    def load_from_uuid(self, uuid: UUID) -> Account | None: ...
    def load_from_username(self, username: str) -> Account | None: ...

    def remove_from_uuid(self, uuid: UUID) -> Account | None: ...
    def remove_from_username(self, username: str) -> Account | None: ...
    
    def store(self, account: Account) -> None: ...
