from typing import Self
from os import PathLike
from enum import Enum, auto
from subprocess import Popen


class Installer:

    def __new__(cls, version: str) -> Self: ...

    def __repr__(self) -> str: ...

    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str): ...

    @property
    def versions_dir(self) -> str: ...
    @versions_dir.setter
    def versions_dir(self, dir: str | PathLike[str]): ...

    @property
    def libraries_dir(self) -> str: ...
    @libraries_dir.setter
    def libraries_dir(self, dir: str | PathLike[str]): ...

    @property
    def assets_dir(self) -> str: ...
    @assets_dir.setter
    def assets_dir(self, dir: str | PathLike[str]): ...
    
    @property
    def jvm_dir(self) -> str: ...
    @jvm_dir.setter
    def jvm_dir(self, dir: str | PathLike[str]): ...

    @property
    def bin_dir(self) -> str: ...
    @bin_dir.setter
    def bin_dir(self, dir: str | PathLike[str]): ...

    @property
    def mc_dir(self) -> str: ...
    @mc_dir.setter
    def mc_dir(self, dir: str | PathLike[str]): ...

    # Not a property because it sets all others dirs!
    def set_main_dir(self, dir: str | PathLike[str]) -> None: ...

    @property
    def strict_assets_check(self) -> bool: ...
    @strict_assets_check.setter
    def strict_assets_check(self, strict: bool): ...

    @property
    def strict_libraries_check(self) -> bool: ...
    @strict_libraries_check.setter
    def strict_libraries_check(self, strict: bool): ...

    @property
    def strict_jvm_check(self) -> bool: ...
    @strict_jvm_check.setter
    def strict_jvm_check(self, strict: bool): ...

    @property
    def jvm_policy(self) -> str | JvmPolicy: ...
    @jvm_policy.setter
    def jvm_policy(self, policy: str | PathLike[str] | JvmPolicy): ...

    @property
    def launcher_name(self) -> str: ...
    @launcher_name.setter
    def launcher_name(self, name: str): ...

    @property
    def launcher_version(self) -> str: ...
    @launcher_version.setter
    def launcher_version(self, name: str): ...

    def install(self) -> Game: ...


class JvmPolicy(Enum):
    System = auto()
    Mojang = auto()
    SystemThenMojang = auto()
    MojangThenSystem = auto()


# class Handler:

#     def filter_features(self, features: set[str]): ...
#     def loaded_features(self, features: set[str]): ...

#     def load_hierarchy(self, root_version: str): ...
#     def loaded_hierarchy(self, hierarchy: list[LoadedVersion]): ...

#     def load_version(self, version: str, file: str): ...
#     def need_version(self, version: str, file: str) -> bool: ...
#     def loaded_version(self, version: str, file: str): ...


# class LoadedVersion:

#     @property
#     def name(self) -> str: ...

#     @property
#     def dir(self) -> str: ...

#     @property
#     def channel(self) -> VersionChannel: ...


# class VersionChannel(Enum):
#     Release = auto()
#     Snapshot = auto()
#     Beta = auto()
#     Alpha = auto()


# class LoadedLibrary:

#     @property
#     def gav(self) -> str: ...
#     @gav.setter
#     def gav(self, gav: str): ...

#     @property
#     def path(self) -> str | None: ...
#     @path.setter
#     def path(self, path: str | PathLike[str] | None): ...

#     @property
#     def download(self) -> LibraryDownload | None: ...
#     @download.setter
#     def download(self, download: LibraryDownload | None): ...

#     @property
#     def natives(self) -> bool: ...
#     @natives.setter
#     def natives(self, natives: bool): ...


# class LibraryDownload:

#     @property
#     def url(self) -> str: ...
#     @url.setter
#     def url(self, url: str): ...

#     @property
#     def size(self) -> int | None: ...
#     @size.setter
#     def size(self, size: int | None): ...

#     @property
#     def sha1(self) -> bytes | None: ...
#     @sha1.setter
#     def sha1(self, sha1: bytes | None): ...


class Game:

    def __repr__(self) -> str: ...
    
    def command(self) -> type[Popen]: ...


def default_main_dir() -> str | None: ...
