from typing import Self, Iterator
from uuid import UUID
from os import PathLike


class Batch:

    def __new__(cls) -> Self: ...

    def __len__(self) -> int: ...

    def __getitem__(self, index: int) -> Entry: ...

    def push(self, url: str, file: str | PathLike[str]) -> Entry: ...
    def push_cached(self, url: str) -> Entry: ...

    def download(self, handler: None) -> BatchResult: ...


class EntryCore:

    @property
    def url(self) -> str: ...
    @property
    def file(self) -> str: ...


class Entry(EntryCore):

    @property
    def expected_size(self) -> int: ...
    @expected_size.setter
    def expected_size(self, size: int | None): ...

    @property
    def expected_sha1(self) -> bytes: ...
    @expected_sha1.setter
    def expected_sha1(self, sha1: bytes | bytearray | None): ...

    def set_expected_size(self, size: int | None) -> Self: ...
    def set_expected_sha1(self, sha1: bytes | bytearray | None) -> Self: ...
    def set_cache_mode(self) -> Self: ...


class BatchResult:

    def __len__(self) -> int: ...

    def __getitem__(self, index: int) -> EntrySuccess | EntryError: ...

    @property
    def errors_count(self) -> int: ...
    @property
    def successes_count(self) -> int: ...

    def iter_successes(self) -> Iterator[EntrySuccess]: ...
    def iter_errors(self) -> Iterator[EntryError]: ...


class EntrySuccess(EntryCore):
    
    @property
    def size(self) -> int: ...
    @property
    def sha1(self) -> bytes: ...


class EntryError(EntryCore): ...
