from typing import Self
from os import PathLike


class GameVersion:
    class Stable:
        def __new__(cls) -> Self: ...
    class Unstable:
        def __new__(cls) -> Self: ...
    class Name:
        def __new__(cls, name: str) -> Self: ...

class LoaderVersion:
    class Stable:
        def __new__(cls) -> Self: ...
    class Unstable:
        def __new__(cls) -> Self: ...
    class Name:
        def __new__(cls, name: str) -> Self: ...

class FabricInstaller:
    def __new__(cls, game_version: str | GameVersion | None = None, loader_version: str | LoaderVersion | None = None, main_dir: str | PathLike[str] | None = None) -> Self: ...
