from typing import Self
from os import PathLike
from enum import Enum, auto

class JvmPolicy(Enum):
    System = auto()
    Mojang = auto()
    SystemThenMojang = auto()
    MojangThenSystem = auto()

class Installer:

    def __new__(cls, version: str) -> Self: ...

    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str): ...

    @property
    def versions_dir(self) -> str: ...
    @versions_dir.setter
    def versions_dir(self, dir: str | PathLike[str]): ...

    @property
    def libraries_dir(self) -> str: ...
    @libraries_dir.setter
    def libraries_dir(self, dir: str | PathLike[str]): ...

    @property
    def assets_dir(self) -> str: ...
    @assets_dir.setter
    def assets_dir(self, dir: str | PathLike[str]): ...
    
    @property
    def jvm_dir(self) -> str: ...
    @jvm_dir.setter
    def jvm_dir(self, dir: str | PathLike[str]): ...

    @property
    def bin_dir(self) -> str: ...
    @bin_dir.setter
    def bin_dir(self, dir: str | PathLike[str]): ...

    @property
    def mc_dir(self) -> str: ...
    @mc_dir.setter
    def mc_dir(self, dir: str | PathLike[str]): ...

    # Not a property because it sets all others dirs!
    def set_main_dir(self, dir: str | PathLike[str]): ...

    @property
    def strict_assets_check(self) -> bool: ...
    @strict_assets_check.setter
    def strict_assets_check(self, strict: bool): ...

    @property
    def strict_libraries_check(self) -> bool: ...
    @strict_libraries_check.setter
    def strict_libraries_check(self, strict: bool): ...

    @property
    def strict_jvm_check(self) -> bool: ...
    @strict_jvm_check.setter
    def strict_jvm_check(self, strict: bool): ...

    @property
    def jvm_policy(self) -> str | JvmPolicy: ...
    @jvm_policy.setter
    def jvm_policy(self, policy: str | PathLike[str] | JvmPolicy): ...

    @property
    def launcher_name(self) -> str: ...
    @launcher_name.setter
    def launcher_name(self, name: str): ...

    @property
    def launcher_version(self) -> str: ...
    @launcher_version.setter
    def launcher_version(self, name: str): ...

    def install(self) -> Game: ...

class Handler:

    def filter_features(self, features: set[str]): ...
    def loaded_features(self, features: set[str]): ...

    def load_hierarchy(self, root_version: str): ...
    def loaded_hierarchy(self, hierarchy: list[str]): ...

    def load_version(self, version: str, file: str): ...
    def need_version(self, version: str, file: str) -> bool: ...
    def loaded_version(self, version: str, file: str): ...

class Game:

    def __new__(cls) -> Self: ...
    
    @property
    def mc_dir(self) -> str: ...
    @mc_dir.setter
    def mc_dir(self, mc_dir: str | PathLike[str]): ...
    
    @property
    def jvm_file(self) -> str: ...
    @jvm_file.setter
    def jvm_file(self, jvm_file: str | PathLike[str]): ...
    
    @property
    def main_class(self) -> str: ...
    @main_class.setter
    def main_class(self, main_class: str): ...
    
    @property
    def jvm_args(self) -> list[str]: ...

    @property
    def game_args(self) -> list[str]: ...

def default_main_dir() -> str | None: ...
