from typing import Self
from os import PathLike
from enum import Enum, auto

class JvmPolicy(Enum):
    System = auto()
    Mojang = auto()
    SystemThenMojang = auto()
    MojangThenSystem = auto()

class Installer:

    def __new__(cls, version: str) -> Self: ...

    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, version: str): ...

    @property
    def versions_dir(self) -> str: ...
    @versions_dir.setter
    def versions_dir(self, dir: str | PathLike[str]): ...

    @property
    def libraries_dir(self) -> str: ...
    @libraries_dir.setter
    def libraries_dir(self, dir: str | PathLike[str]): ...

    @property
    def assets_dir(self) -> str: ...
    @assets_dir.setter
    def assets_dir(self, dir: str | PathLike[str]): ...
    
    @property
    def jvm_dir(self) -> str: ...
    @jvm_dir.setter
    def jvm_dir(self, dir: str | PathLike[str]): ...

    @property
    def bin_dir(self) -> str: ...
    @bin_dir.setter
    def bin_dir(self, dir: str | PathLike[str]): ...

    @property
    def mc_dir(self) -> str: ...
    @mc_dir.setter
    def mc_dir(self, dir: str | PathLike[str]): ...

    # Not a property because it sets all others dirs!
    def set_main_dir(self, dir: str | PathLike[str]): ...

    @property
    def strict_assets_check(self) -> bool: ...
    @strict_assets_check.setter
    def strict_assets_check(self, strict: bool): ...

    @property
    def strict_libraries_check(self) -> bool: ...
    @strict_libraries_check.setter
    def strict_libraries_check(self, strict: bool): ...

    @property
    def strict_jvm_check(self) -> bool: ...
    @strict_jvm_check.setter
    def strict_jvm_check(self, strict: bool): ...

    @property
    def jvm_policy(self) -> str | JvmPolicy: ...
    @jvm_policy.setter
    def jvm_policy(self, policy: str | PathLike[str] | JvmPolicy): ...

    @property
    def launcher_name(self) -> str: ...
    @launcher_name.setter
    def launcher_name(self, name: str): ...

    @property
    def launcher_version(self) -> str: ...
    @launcher_version.setter
    def launcher_version(self, name: str): ...

def default_main_dir() -> str | None: ...
