/* automatically generated by rust-bindgen 0.72.0 */

pub type size_t = ::std::ffi::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_msa_auth {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_msa_device_code_flow {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_msa_account {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_msa_database {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_game {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_base {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_moj {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_fabric {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_forge {
    _unused: [u8; 0],
}
#[doc = " An array of 16 bytes representing an UUID."]
pub type pmc_uuid = [u8; 16usize];
#[doc = " An array of 16 bytes representing an UUID."]
pub type pmc_sha1 = [u8; 20usize];
#[repr(u32)]
#[doc = " The code of all errors."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum pmc_err_tag {
    PMC_ERR_UNSET = 0,
    PMC_ERR_INTERNAL = 1,
    PMC_ERR_MSA_AUTH_DECLINED = 16,
    PMC_ERR_MSA_AUTH_TIMED_OUT = 17,
    PMC_ERR_MSA_AUTH_OUTDATED_TOKEN = 18,
    PMC_ERR_MSA_AUTH_DOES_NOT_OWN_GAME = 19,
    PMC_ERR_MSA_AUTH_INVALID_STATUS = 20,
    PMC_ERR_MSA_AUTH_UNKNOWN = 21,
    PMC_ERR_MSA_DATABASE_IO = 32,
    PMC_ERR_MSA_DATABASE_CORRUPTED = 33,
    PMC_ERR_MSA_DATABASE_WRITE_FAILED = 34,
    PMC_ERR_BASE_HIERARCHY_LOOP = 48,
    PMC_ERR_BASE_VERSION_NOT_FOUND = 49,
    PMC_ERR_BASE_ASSETS_NOT_FOUND = 50,
    PMC_ERR_BASE_CLIENT_NOT_FOUND = 51,
    PMC_ERR_BASE_LIBRARY_NOT_FOUND = 52,
    PMC_ERR_BASE_JVM_NOT_FOUND = 53,
    PMC_ERR_BASE_MAIN_CLASS_NOT_FOUND = 54,
    PMC_ERR_BASE_DOWNLOAD_RESOURCES_CANCELLED = 55,
    PMC_ERR_BASE_DOWNLOAD = 56,
    PMC_ERR_MOJ_LWJGL_FIX_NOT_FOUND = 64,
    PMC_ERR_FABRIC_LATEST_VERSION_NOT_FOUND = 80,
    PMC_ERR_FABRIC_GAME_VERSION_NOT_FOUND = 81,
    PMC_ERR_FABRIC_LOADER_VERSION_NOT_FOUND = 82,
    PMC_ERR_FORGE_LATEST_VERSION_NOT_FOUND = 96,
    PMC_ERR_FORGE_INSTALLER_NOT_FOUND = 97,
    PMC_ERR_FORGE_MAVEN_METADATA_MALFORMED = 98,
    PMC_ERR_FORGE_INSTALLER_PROFILE_NOT_FOUND = 99,
    PMC_ERR_FORGE_INSTALLER_PROFILE_INCOHERENT = 100,
    PMC_ERR_FORGE_INSTALLER_VERSION_METADATA_NOT_FOUND = 101,
    PMC_ERR_FORGE_INSTALLER_FILE_NOT_FOUND = 102,
    PMC_ERR_FORGE_INSTALLER_PROCESSOR_NOT_FOUND = 103,
    PMC_ERR_FORGE_INSTALLER_PROCESSOR_FAILED = 104,
    PMC_ERR_FORGE_INSTALLER_PROCESSOR_CORRUPTED = 105,
}
#[doc = " PMC_ERR_INTERNAL"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_data_internal {
    pub origin: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_MSA_AUTH_INVALID_STATUS"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_data_msa_auth_invalid_status {
    pub status: u16,
}
#[doc = " PMC_ERR_MSA_AUTH_UNKNOWN"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_data_msa_auth_unknown {
    pub message: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_BASE_HIERARCHY_LOOP"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_base_hierarchy_loop {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_BASE_VERSION_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_base_version_not_found {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_BASE_ASSETS_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_base_assets_not_found {
    pub id: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_BASE_LIBRARY_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_base_library_not_found {
    pub name: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_BASE_JVM_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_base_jvm_not_found {
    pub major_version: u32,
}
#[doc = " PMC_ERR_MOJ_LWJGL_FIX_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_moj_lwjgl_fix_not_found {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FABRIC_LATEST_VERSION_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_fabric_latest_version_not_found {
    pub game_version: *const ::std::ffi::c_char,
    pub stable: bool,
}
#[doc = " PMC_ERR_FABRIC_GAME_VERSION_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_fabric_game_version_not_found {
    pub game_version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FABRIC_LOADER_VERSION_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_fabric_loader_version_not_found {
    pub game_version: *const ::std::ffi::c_char,
    pub loader_version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FORGE_LATEST_VERSION_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_latest_version_not_found {
    pub game_version: *const ::std::ffi::c_char,
    pub stable: bool,
}
#[doc = " PMC_ERR_FORGE_INSTALLER_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_installer_not_found {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FORGE_INSTALLER_FILE_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_installer_file_not_found {
    pub entry: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FORGE_INSTALLER_PROCESSOR_NOT_FOUND"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_installer_processor_not_found {
    pub name: *const ::std::ffi::c_char,
}
#[doc = " PMC_ERR_FORGE_INSTALLER_PROCESSOR_FAILED"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_installer_processor_failed {
    pub name: *const ::std::ffi::c_char,
    pub status: ::std::ffi::c_int,
    pub stdout: *const ::std::ffi::c_char,
    pub stdout_len: size_t,
    pub stderr: *const ::std::ffi::c_char,
    pub stderr_len: size_t,
}
#[doc = " PMC_ERR_FORGE_INSTALLER_PROCESSOR_CORRUPTED"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_err_forge_installer_processor_corrupted {
    pub name: *const ::std::ffi::c_char,
    pub file: *const ::std::ffi::c_char,
    pub expected_sha1: *const pmc_sha1,
}
#[doc = " The union of all data types for errors."]
#[repr(C)]
#[derive(Copy, Clone)]
pub union pmc_err_data {
    pub _none: ::std::ffi::c_int,
    pub internal: pmc_err_data_internal,
    pub msa_auth_invalid_status: pmc_err_data_msa_auth_invalid_status,
    pub msa_auth_unknown: pmc_err_data_msa_auth_unknown,
    pub base_hierarchy_loop: pmc_err_base_hierarchy_loop,
    pub base_version_not_found: pmc_err_base_version_not_found,
    pub base_assets_not_found: pmc_err_base_assets_not_found,
    pub base_library_not_found: pmc_err_base_library_not_found,
    pub base_jvm_not_found: pmc_err_base_jvm_not_found,
    pub moj_lwjgl_fix_not_found: pmc_err_moj_lwjgl_fix_not_found,
    pub fabric_latest_version_not_found: pmc_err_fabric_latest_version_not_found,
    pub fabric_game_version_not_found: pmc_err_fabric_game_version_not_found,
    pub fabric_loader_version_not_found: pmc_err_fabric_loader_version_not_found,
    pub forge_latest_version_not_found: pmc_err_forge_latest_version_not_found,
    pub forge_installer_not_found: pmc_err_forge_installer_not_found,
    pub forge_installer_file_not_found: pmc_err_forge_installer_file_not_found,
    pub forge_installer_processor_not_found: pmc_err_forge_installer_processor_not_found,
    pub forge_installer_processor_failed: pmc_err_forge_installer_processor_failed,
    pub forge_installer_processor_corrupted: pmc_err_forge_installer_processor_corrupted,
}
#[doc = " Generic error type, you should usually use this type by defining a null-pointer to it\n and passing a pointer to that pointer to any function that accepts it. If an error\n happens, the function will allocate an error and then write its pointer in the given\n location. The error should be freed afterward.\n\n This structure has a known layout in C."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pmc_err {
    #[doc = " Tag of the error."]
    pub tag: pmc_err_tag,
    #[doc = " The data of the tag, that can be used depending on the error tag."]
    pub data: pmc_err_data,
    #[doc = " The descriptive human-readable message for the error."]
    pub message: *const ::std::ffi::c_char,
}
#[repr(u32)]
#[doc = " The tag for the pmc_jvm_policy tagged union."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum pmc_jvm_policy_tag {
    PMC_JVM_POLICY_STATIC = 0,
    PMC_JVM_POLICY_SYSTEM = 1,
    PMC_JVM_POLICY_MOJANG = 2,
    PMC_JVM_POLICY_SYSTEM_THEN_MOJANG = 3,
    PMC_JVM_POLICY_MOJANG_THEN_SYSTEM = 4,
}
#[doc = " The JVM policy tagged union, only the static policy requires an explicit path value."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_jvm_policy {
    pub tag: pmc_jvm_policy_tag,
    pub static_path: *const ::std::ffi::c_char,
}
#[repr(u32)]
#[doc = " Represent the release channel for a version."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum pmc_version_channel {
    PMC_VERSION_CHANNEL_RELEASE = 0,
    PMC_VERSION_CHANNEL_SNAPSHOT = 1,
    PMC_VERSION_CHANNEL_BETA = 2,
    PMC_VERSION_CHANNEL_ALPHA = 3,
}
#[doc = " Represent a version loaded during the installation."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_loaded_version {
    pub name: *const ::std::ffi::c_char,
    pub dir: *const ::std::ffi::c_char,
    pub channel: pmc_version_channel,
}
#[doc = " Represent a version loaded during the installation."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_library_download {
    pub url: *const ::std::ffi::c_char,
    pub size: u32,
    pub sha1: *const pmc_sha1,
}
#[doc = " Represent a version loaded during the installation."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_loaded_library {
    pub gav: *const ::std::ffi::c_char,
    pub path: *const ::std::ffi::c_char,
    pub download: *const pmc_library_download,
    pub natives: bool,
}
#[repr(u32)]
#[doc = " The code of all events."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum pmc_event_tag {
    PMC_EVENT_BASE_FILTER_FEATURES = 0,
    PMC_EVENT_BASE_LOADED_FEATURES = 1,
    PMC_EVENT_BASE_LOAD_HIERARCHY = 2,
    PMC_EVENT_BASE_LOADED_HIERARCHY = 3,
    PMC_EVENT_BASE_LOAD_VERSION = 4,
    PMC_EVENT_BASE_NEED_VERSION = 5,
    PMC_EVENT_BASE_LOADED_VERSION = 6,
    PMC_EVENT_BASE_LOAD_CLIENT = 7,
    PMC_EVENT_BASE_LOADED_CLIENT = 8,
    PMC_EVENT_BASE_LOAD_LIBRARIES = 9,
    PMC_EVENT_BASE_FILTER_LIBRARIES = 10,
    PMC_EVENT_BASE_LOADED_LIBRARIES = 11,
    PMC_EVENT_BASE_FILTER_LIBRARIES_FILES = 12,
    PMC_EVENT_BASE_LOADED_LIBRARIES_FILES = 13,
    PMC_EVENT_BASE_NO_LOGGER = 14,
    PMC_EVENT_BASE_LOAD_LOGGER = 15,
    PMC_EVENT_BASE_LOADED_LOGGER = 16,
    PMC_EVENT_BASE_NO_ASSETS = 17,
    PMC_EVENT_BASE_LOAD_ASSETS = 18,
    PMC_EVENT_BASE_LOADED_ASSETS = 19,
    PMC_EVENT_BASE_VERIFIED_ASSETS = 20,
    PMC_EVENT_BASE_LOAD_JVM = 21,
    PMC_EVENT_BASE_FOUND_JVM_VERSION = 22,
    PMC_EVENT_BASE_WARN_JVM_UNSUPPORTED_DYNAMIC_CTR = 23,
    PMC_EVENT_BASE_WARN_JVM_UNSUPPORTED_PLATFORM = 24,
    PMC_EVENT_BASE_WARN_JVM_MISSING_DISTRIBUTION = 25,
    PMC_EVENT_BASE_LOADED_JVM = 26,
    PMC_EVENT_BASE_DOWNLOAD_RESOURCES = 27,
    PMC_EVENT_BASE_DOWNLOAD_PROGRESS = 28,
    PMC_EVENT_BASE_DOWNLOADED_RESOURCES = 29,
    PMC_EVENT_BASE_EXTRACTED_BINARIES = 30,
    PMC_EVENT_MOJ_INVALIDATED_VERSION = 80,
    PMC_EVENT_MOJ_FETCH_VERSION = 81,
    PMC_EVENT_MOJ_FETCHED_VERSION = 82,
    PMC_EVENT_MOJ_FIXED_LEGACY_QUICK_PLAY = 83,
    PMC_EVENT_MOJ_FIXED_LEGACY_PROXY = 84,
    PMC_EVENT_MOJ_FIXED_LEGACY_MERGE_SORT = 85,
    PMC_EVENT_MOJ_FIXED_LEGACY_RESOLUTION = 86,
    PMC_EVENT_MOJ_FIXED_BROKEN_AUTHLIB = 87,
    PMC_EVENT_MOJ_WARN_UNSUPPORTED_QUICK_PLAY = 88,
    PMC_EVENT_MOJ_WARN_UNSUPPORTED_RESOLUTION = 89,
    PMC_EVENT_FABRIC_FETCH_VERSION = 96,
    PMC_EVENT_FABRIC_FETCHED_VERSION = 97,
    PMC_EVENT_FORGE_INSTALLING = 112,
    PMC_EVENT_FORGE_FETCH_INSTALLER = 113,
    PMC_EVENT_FORGE_FETCHED_INSTALLER = 114,
    PMC_EVENT_FORGE_INSTALLING_GAME = 115,
    PMC_EVENT_FORGE_FETCH_INSTALLER_LIBRARIES = 116,
    PMC_EVENT_FORGE_FETCHED_INSTALLER_LIBRARIES = 117,
    PMC_EVENT_FORGE_RUN_INSTALLER_PROCESSOR = 118,
    PMC_EVENT_FORGE_INSTALLED = 119,
}
#[doc = " PMC_EVENT_BASE_LOADED_FEATURES"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_features {
    pub features: *const *const ::std::ffi::c_char,
    pub features_len: size_t,
}
#[doc = " PMC_EVENT_BASE_LOAD_HIERARCHY"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_load_hierarchy {
    pub root_version: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_BASE_LOADED_HIERARCHY"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_hierarchy {
    pub hierarchy: *const pmc_loaded_version,
    pub hierarchy_len: size_t,
}
#[doc = " PMC_EVENT_BASE_LOAD_VERSION, PMC_EVENT_BASE_LOADED_VERSION"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_load_version {
    pub version: *const ::std::ffi::c_char,
    pub file: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_BASE_LOAD_VERSION, PMC_EVENT_BASE_LOADED_VERSION"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_version(pub pmc_event_base_load_version);
#[doc = " PMC_EVENT_BASE_NEED_VERSION"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_need_version {
    pub version: *const ::std::ffi::c_char,
    pub file: *const ::std::ffi::c_char,
    pub retry: *mut bool,
}
#[doc = " PMC_EVENT_BASE_LOADED_VERSION"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_client {
    pub file: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_BASE_LOADED_LIBRARIES"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_libraries {
    pub libraries: *const pmc_loaded_library,
    pub libraries_len: size_t,
}
#[doc = " PMC_EVENT_BASE_LOADED_LIBRARIES_FILES"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_libraries_files {
    pub class_files: *const *const ::std::ffi::c_char,
    pub class_files_len: size_t,
    pub natives_files: *const *const ::std::ffi::c_char,
    pub natives_files_len: size_t,
}
#[doc = " PMC_EVENT_BASE_LOAD_LOGGER, PMC_EVENT_BASE_LOADED_LOGGER"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_load_logger {
    pub id: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_BASE_LOAD_LOGGER, PMC_EVENT_BASE_LOADED_LOGGER"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_logger(pub pmc_event_base_load_logger);
#[doc = " PMC_EVENT_BASE_LOAD_ASSETS, PMC_EVENT_BASE_LOADED_ASSETS, PMC_EVENT_BASE_VERIFIED_ASSETS"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_load_assets {
    pub id: *const ::std::ffi::c_char,
    pub count: size_t,
}
#[doc = " PMC_EVENT_BASE_LOAD_ASSETS, PMC_EVENT_BASE_LOADED_ASSETS, PMC_EVENT_BASE_VERIFIED_ASSETS"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_assets(pub pmc_event_base_load_assets);
#[doc = " PMC_EVENT_BASE_LOAD_ASSETS, PMC_EVENT_BASE_LOADED_ASSETS, PMC_EVENT_BASE_VERIFIED_ASSETS"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_verified_assets(pub pmc_event_base_load_assets);
#[doc = " PMC_EVENT_BASE_FOUND_JVM_VERSION, PMC_EVENT_BASE_LOADED_JVM"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_found_jvm_system_version {
    pub file: *const ::std::ffi::c_char,
    pub version: *const ::std::ffi::c_char,
    pub compatible: bool,
}
#[doc = " PMC_EVENT_BASE_FOUND_JVM_VERSION, PMC_EVENT_BASE_LOADED_JVM"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_loaded_jvm(pub pmc_event_base_found_jvm_system_version);
#[doc = " PMC_EVENT_BASE_DOWNLOAD_RESOURCES"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_download_resources {
    pub cancel: bool,
}
#[doc = " PMC_EVENT_BASE_DOWNLOAD_PROGRESS"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_download_progress {
    pub count: size_t,
    pub total_count: size_t,
    pub size: size_t,
    pub total_size: size_t,
}
#[doc = " PMC_EVENT_BASE_EXTRACTED_BINARIES"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_base_extracted_binaries {
    pub dir: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_MOJ_INVALIDATED_VERSION, PMC_EVENT_MOJ_FETCH_VERSION, PMC_EVENT_MOJ_FETCHED_VERSION"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_moj_invalidated_version {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_MOJ_INVALIDATED_VERSION, PMC_EVENT_MOJ_FETCH_VERSION, PMC_EVENT_MOJ_FETCHED_VERSION"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_moj_fetch_version(pub pmc_event_moj_invalidated_version);
#[doc = " PMC_EVENT_MOJ_INVALIDATED_VERSION, PMC_EVENT_MOJ_FETCH_VERSION, PMC_EVENT_MOJ_FETCHED_VERSION"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_moj_fetched_version(pub pmc_event_moj_invalidated_version);
#[doc = " PMC_EVENT_MOJ_FIXED_LEGACY_PROXY"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_moj_fixed_legacy_proxy {
    pub host: *const ::std::ffi::c_char,
    pub port: u16,
}
#[doc = " PMC_EVENT_FABRIC_FETCH_VERSION, PMC_EVENT_FABRIC_FETCHED_VERSION"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_fabric_fetch_version {
    pub game_version: *const ::std::ffi::c_char,
    pub loader_version: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_FABRIC_FETCH_VERSION, PMC_EVENT_FABRIC_FETCHED_VERSION"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_fabric_fetched_version(pub pmc_event_fabric_fetch_version);
#[doc = " PMC_EVENT_FORGE_INSTALLING"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_forge_installing {
    pub tmp_dir: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_FORGE_FETCH_INSTALLER, PMC_EVENT_FORGE_FETCHED_INSTALLER"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_forge_fetch_installer {
    pub version: *const ::std::ffi::c_char,
}
#[doc = " PMC_EVENT_FORGE_FETCH_INSTALLER, PMC_EVENT_FORGE_FETCHED_INSTALLER"]
#[repr(transparent)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_forge_fetched_installer(pub pmc_event_forge_fetch_installer);
#[doc = " PMC_EVENT_FORGE_RUN_INSTALLER_PROCESSOR"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmc_event_forge_run_installer_processor {
    pub name: *const ::std::ffi::c_char,
    pub task: *const ::std::ffi::c_char,
}
#[doc = " The data accompanying an event, when relevant."]
#[repr(C)]
#[derive(Copy, Clone)]
pub union pmc_event_data {
    pub _none: ::std::ffi::c_int,
    pub base_loaded_features: pmc_event_base_loaded_features,
    pub base_load_hierarchy: pmc_event_base_load_hierarchy,
    pub base_loaded_hierarchy: pmc_event_base_loaded_hierarchy,
    pub base_load_version: pmc_event_base_load_version,
    pub base_loaded_version: pmc_event_base_loaded_version,
    pub base_need_version: pmc_event_base_need_version,
    pub base_loaded_client: pmc_event_base_loaded_client,
    pub base_loaded_libraries: pmc_event_base_loaded_libraries,
    pub base_loaded_libraries_files: pmc_event_base_loaded_libraries_files,
    pub base_load_logger: pmc_event_base_load_logger,
    pub base_loaded_logger: pmc_event_base_loaded_logger,
    pub base_load_assets: pmc_event_base_load_assets,
    pub base_loaded_assets: pmc_event_base_loaded_assets,
    pub base_verified_assets: pmc_event_base_verified_assets,
    pub base_found_jvm_system_version: pmc_event_base_found_jvm_system_version,
    pub base_loaded_jvm: pmc_event_base_loaded_jvm,
    pub base_download_resources: pmc_event_base_download_resources,
    pub base_download_progress: pmc_event_base_download_progress,
    pub base_extracted_binaries: pmc_event_base_extracted_binaries,
    pub moj_invalidated_version: pmc_event_moj_invalidated_version,
    pub moj_fetch_version: pmc_event_moj_fetch_version,
    pub moj_fetched_version: pmc_event_moj_fetched_version,
    pub moj_fixed_legacy_proxy: pmc_event_moj_fixed_legacy_proxy,
    pub fabric_fetch_version: pmc_event_fabric_fetch_version,
    pub fabric_fetched_version: pmc_event_fabric_fetched_version,
    pub forge_installing: pmc_event_forge_installing,
    pub forge_fetch_installer: pmc_event_forge_fetch_installer,
    pub forge_fetched_installer: pmc_event_forge_fetched_installer,
    pub forge_run_installer_processor: pmc_event_forge_run_installer_processor,
}
#[doc = " The full event structure."]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct pmc_event {
    pub tag: pmc_event_tag,
    pub data: pmc_event_data,
}
#[doc = " A generic event handler."]
pub type pmc_handler = ::std::option::Option<unsafe extern "C" fn(event: *mut pmc_event)>;
